# Generated by Django 5.2.1 on 2025-06-23 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intervention', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
