# Generated by Django 4.2.11 on 2025-06-24 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intervention', '0004_parentchildlinkrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='login_id',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
    ]
